### ISSUE TITLE
Installing the latest interim version on a clean Eclipse 2023-09 fails

### ISSUE THREAD

**Issue by kolovos** [eclipse/epsilon#60]
Installing the latest interim version on a clean Eclipse 2023-09 fails with the following error message

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: Picto 2.5.0.202310161253 (org.eclipse.epsilon.picto.feature.feature.group 2.5.0.202310161253)
  Missing requirement: Picto 2.5.0.202310161253 (org.eclipse.epsilon.picto 2.5.0.202310161253) requires 'osgi.bundle; wrapped.net.sourceforge.plantuml.plantuml-epl 1.2023.11' but it could not be found
  Cannot satisfy dependency:
    From: Picto 2.5.0.202310161253 (org.eclipse.epsilon.picto.feature.feature.group 2.5.0.202310161253)
    To: org.eclipse.equinox.p2.iu; org.eclipse.epsilon.picto [2.5.0.202310161253,2.5.0.202310161253]
```

@alfonsodelavega can you reproduce this?

_Originally posted by @kolovos in https://github.com/eclipse/epsilon/issues/59#issuecomment-1766455695_

**Comment by alfonsodelavega** [comment]
Yes, I can reproduce the same issue (both from the interim url and from a local update site)

The issue can be fixed by including the feature that is generated with PlantUML's maven dependency into Picto's feature:

```
diff --git a/features/org.eclipse.epsilon.picto.feature/feature.xml b/features/org.eclipse.epsilon.picto.feature/feature.xml
index 3a8c232f7..c3d5431f3 100644
--- a/features/org.eclipse.epsilon.picto.feature/feature.xml
+++ b/features/org.eclipse.epsilon.picto.feature/feature.xml
@@ -22,6 +22,10 @@
          id="org.eclipse.epsilon.flexmi.dt.feature"
          version="2.5.0.qualifier"/>
 
+   <includes
+         id="net.sourceforge.plantuml"
+         version="0.0.0"/>
+
    <plugin
          id="org.eclipse.epsilon.picto"
          download-size="0"
```

However I'm not sure if that is what we want to do with every dependency that we pull from Maven in the future. For the time being, I've reverted the PlantUML bump, so that the installer works again. The installation issue can be tested offline with the local updatesite.

I guess the ideal situation would be for Maven dependencies to be usable as wrapped plugins *and* automatically detected and fetched when installing features. Any thoughts? Maybe @agarciadom or @arcanefoam have faced a similar thing before.

**Comment by alfonsodelavega** [comment]
Issue fixed by adding necessary plugins to the feature directly. This is needed at the moment for dependencies pulled directly from Maven (which are automatically wrapped as plugins).

Described also at the [commit message](https://github.com/eclipse/epsilon/commit/84e1663f846ab9e336366ed628a445a8d8fcf401)
